### ISSUE TITLE
Disable typekit in testing?

### ISSUE THREAD

**Issue by MattMSumner** [sportly/ember-cli-typekit#3]
Is there currently a way to do this? This would be to avoid some CI services from timing out.

**Comment by MattMSumner** [comment]
So setting sync to true got CI passing but this might still be worth adding?

**Comment by MattMSumner** [comment]
Opened a PR: https://github.com/sportly/ember-cli-typekit/pull/4

**Comment by kylenathan** [comment]
Thanks @MattMSumner  - PR #4 merged and v0.0.4 published

**Comment by MattMSumner** [comment]
Sweet!
